### ISSUE TITLE
Missing APIs for frontend

### ISSUE THREAD

**Issue by kaitoz11** [EventGateFPTU/wowtogo-BE#60]
- [x] Get all orders by eventId
- [x] Get all check-ins by event
- [x] Get all tickets of current user
- [x] Create returns data object - @PersieDaCoder 
- [x] #70
- [x] #68

**Comment by kaitoz11** [comment]
- [ ] Get Organizer of current user
- [ ] Get Organizer by Id

**Comment by PersieDaCoder** [comment]
- [ ] Refactor Get Ticket Type Of Event

**Comment by kaitoz11** [comment]
Please close this issue after this task @PersieDaCoder 

> * [ ]  Refactor Get Ticket Type Of Event

**Comment by kaitoz11** [comment]
Closing this issue
