### ISSUE TITLE
Add authorization logic for update organization API

### ISSUE THREAD

**Issue by kaitoz11** [EventGateFPTU/wowtogo-BE#92]
https://github.com/EventGateFPTU/wowtogo-BE/blob/ffa48c0a2844e97d9c5e02f1ce5e2a5895448d0d/src/UseCases/UC_Organizer/Commands/UpdateOrganizer/UpdateOrganizerHandler.cs#L10-L17

**Comment by trungkien100823** [comment]
current user is organizer, right?

**Comment by kaitoz11** [comment]
> current user is organizer, right?

Exactly
